### PR TITLE
feature: added templates for horizontal pod autoscaling

### PR DESCRIPTION
**Pull request by AngeloB-AIS**
added templates for horizontal pod autoscaling

### CODE REVIEW

**Comment by RafaelOAiSquared** [comment]
@CodiumAI-Agent /review

**Comment by RafaelOAiSquared** [comment]
@AngeloB-AIS deploy this to `staging` and have QA go over it.

**Review by RafaelOAiSquared — APPROVED** [review]

**Comment by subintp** [comment]
@CodiumAI-Agent /review

**Pull request merged**
