### PR TITLE
Feature  add external dns

### PR DESCRIPTION
**Pull request by AngeloB-AIS**
Feature: added external-dns annotations, associated values in values.yaml and made tls via cert-manager conditional

### CODE REVIEW

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /review

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /improve

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /describe

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /improve

**Review by RafaelOAiSquared — APPROVED** [review]

**Review by RafaelOAiSquared — APPROVED** [review]

**Pull request merged**
