### PR TITLE
Feature  disallow privilege escalation

### PR DESCRIPTION
**Pull request by AngeloB-AIS**
Adding required securityContext guardrails to align with the internal VG requirements which are based on kubesec recommendations.

### CODE REVIEW

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /improve
--pr_code_suggestions.num_code_suggestions_per_chunk="5"

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /improve
--pr_code_suggestions.num_code_suggestions_per_chunk="4"

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /review

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /review

**Comment by AngeloB-AIS** [comment]
@CodiumAI-Agent /improve
--pr_code_suggestions.num_code_suggestions_per_chunk="4"

**Review by RafaelOAiSquared — APPROVED** [review]

**Pull request merged**
